In [2]:
## requirements library 
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import pickle 
import streamlit as st 
import tensorboard as tb

In [61]:
## Load the dataset 
df=pd.read_csv('Churn_Modelling.csv')
df.head()
print(df.shape)

(10000, 14)

In [5]:
## Remove the Irrevalent columns 
# like ID , Name, Row, Number 
df=df.drop(['RowNumber'],axis=1)
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

14

In [7]:
## Encoding Categorical Variable
from sklearn.preprocessing import LabelEncoder
lebel_encoder = LabelEncoder()

In [8]:
df['Gender']=lebel_encoder.fit_transform(df['Gender'])
df.head()

,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,15634602,Hargrave,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,15647311,Hill,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,15619304,Onio,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,15701354,Boni,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,15737888,Mitchell,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [11]:
## Then Encode the geographicay column so in this column we apply the onehotencoder 
from sklearn.preprocessing import OneHotEncoder
one_hot=OneHotEncoder()

In [13]:
geo_encoder = one_hot.fit_transform(df[['Geography']])

In [19]:
geo_encoder

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10000 stored elements and shape (10000, 3)>

In [20]:
one_hot.get_feature_names_out(['Geography'])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [21]:
## Convert to array 
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]], shape=(10000, 3))

In [24]:
geo_encoder_data= pd.DataFrame(geo_encoder.toarray(),columns = one_hot.get_feature_names_out(['Geography']))

In [25]:
geo_encoder_data.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [27]:
## Combine the one_hot encoded columns with original data 
df=pd.concat([df.drop('Geography',axis=1),geo_encoder_data],axis=1)
df.head()

,CustomerId,Surname,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,15634602,Hargrave,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,15647311,Hill,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,15619304,Onio,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,15701354,Boni,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,15737888,Mitchell,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [33]:
df=df.drop(['Surname'],axis=1)
df.head()

,CustomerId,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,15634602,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,15647311,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,15619304,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,15701354,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,15737888,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [36]:
## Save the encoder and scaler 
with open('level_encoder_gender.pkl','wb')as file :
    pickle.dump(lebel_encoder,file)
with open('one_hot_encoder.pkl','wb') as file:
    pickle.dump(one_hot,file)

## Divide the dataset into dependent and independent feature

In [39]:
from sklearn.model_selection import train_test_split 
X=df.drop('Exited',axis=1)
y=df['Exited']
print(x.shape)
print(y.shape)

(10000, 13)
(10000,)

In [41]:
## Split the data into train test 
X_train,X_test,y_train,y_test  = train_test_split(X,y,test_size=0.2,random_state=42)
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(8000, 13)
(2000, 13)
(8000,)
(2000,)

In [42]:
## Select the features 
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [46]:
X_train_scale=scaler.fit_transform(X_train)
X_test_scale=scaler.transform(X_test)

In [47]:
## Samve the Scaler Model 
with open('scaler.pkl','wb')as file:
    pickle.dump(scaler,file)

# ANN :- Artficial Neural Network 
## Implementation

In [48]:
import tensorflow as tf

In [50]:
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard
import datetime

In [60]:
X_train.head()

,CustomerId,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
9254,15601116,686,1,32,6,0.00,2,1,1,179093.26,1.0,0.0,0.0
1561,15766374,632,1,42,4,119624.60,2,1,1,195978.86,0.0,1.0,0.0
1670,15716994,559,1,24,3,114739.92,1,1,0,85891.02,0.0,0.0,1.0
6087,15730759,561,0,27,9,135637.00,1,1,0,153080.40,1.0,0.0,0.0
6669,15797900,517,1,56,9,142147.32,1,0,0,39488.04,1.0,0.0,0.0

In [68]:
## Build Our ANN Model 
model = Sequential(
    [
        Dense(64,activation='relu',input_shape=(X_train_scale.shape[1],)),  # HL1
        Dense(32,activation='relu'), # HL2 
        Dense(1,activation='sigmoid') # Output Layer 
    ]
)

In [69]:
model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_11 (Dense)                     │ (None, 64)                  │             896 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_12 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_13 (Dense)                     │ (None, 1)                   │              33 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,009 (11.75 KB)

 Trainable params: 3,009 (11.75 KB)

 Non-trainable params: 0 (0.00 B)

In [74]:
opt=tf.keras.optimizers.Adam(learning_rate=0.01)
loss=tf.keras.losses.BinaryCrossentropy()

In [75]:
## Compile the model  
model.compile(optimizer=opt,loss=loss,metrics=['accuracy'])

In [76]:
## Setup the tensor board 
log_dir='logs/fit' + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")

In [77]:
tensorflow_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [84]:
## Set up Early Stopping 
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=20,restore_best_weights=True)

In [85]:
### Training The Model 
history = model.fit(X_train_scale,y_train,validation_data=(X_test_scale,y_test),epochs=100,callbacks=[tensorflow_callback,early_stopping_callback])

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8661 - loss: 0.3264 - val_accuracy: 0.8605 - val_loss: 0.3506
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8691 - loss: 0.3234 - val_accuracy: 0.8625 - val_loss: 0.3520
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8689 - loss: 0.3195 - val_accuracy: 0.8605 - val_loss: 0.3552
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8699 - loss: 0.3169 - val_accuracy: 0.8615 - val_loss: 0.3607
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8721 - loss: 0.3163 - val_accuracy: 0.8640 - val_loss: 0.3653
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 8ms/step - accuracy: 0.8745 - loss: 0.3120 - val_accuracy: 0.8580 - val_loss: 0.3662
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8751 - loss: 0.3102 - val_accuracy: 0.8595 - val_loss: 0.3698
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - accuracy: 0.8763 - loss: 0.3087 - val_accuracy: 0.8585 - val_loss: 0.3714
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.8769 - loss: 0.3066 - val_accuracy: 0.8600 - val_loss: 0.3752
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8767 - loss: 0.3062 - val_accuracy: 0.8600 - val_loss: 0.3701
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8784 - loss: 0.3030 - val_accuracy: 0.8605 - val_loss: 0.3711
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8800 - loss: 0.2993 - val_accuracy: 0.8605 - val_loss: 0.3822
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8814 - loss: 0.2971 - val_accuracy: 0.8585 - val_loss: 0.3894
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - accuracy: 0.8789 - loss: 0.2997 - val_accuracy: 0.8595 - val_loss: 0.3815
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8815 - loss: 0.2915 - val_accuracy: 0.8575 - val_loss: 0.3936
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8823 - loss: 0.2919 - val_accuracy: 0.8610 - val_loss: 0.3941
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8841 - loss: 0.2864 - val_accuracy: 0.8565 - val_loss: 0.4073
Epoch 18/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8850 - loss: 0.2831 - val_accuracy: 0.8585 - val_loss: 0.4046
Epoch 19/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8823 - loss: 0.2839 - val_accuracy: 0.8535 - val_loss: 0.4117
Epoch 20/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - accuracy: 0.8832 - loss: 0.2855 - val_accuracy: 0.8560 - val_loss: 0.4033
Epoch 21/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.8850 - loss: 0.2798 - val_accuracy: 0.8580 - val_loss: 0.4069

In [87]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [89]:
## Load Tensorboard Extension
%load_ext tensorboard  ## launch tensorboard ext

In [90]:
%tensorboard --logdir  logs/fit