In [2]:
import pandas as pd 
from sklearn.model_selection import train_test_split 
from sklearn.preprocessing import StandardScaler,LabelEncoder , OneHotEncoder 
import pickle

In [3]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [4]:
## Preprocess the data 
data = data.drop(['RowNumber','CustomerId','Surname'],axis=1)
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [5]:
## Encode categorical variables 
label_encoder_gender= LabelEncoder()
data['Gender']=label_encoder_gender.fit_transform(data['Gender'])

In [8]:
## Onehot encode 'Geography '
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns = onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [11]:
 # combine one-hot encoded columns with original data 
data = pd.concat([data.drop('Geography',axis=1),geo_encoded_df],axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [12]:
## Split the data into features and target 
X = data.drop('EstimatedSalary',axis=1)
y=data['EstimatedSalary']
print(X.shape)
print(y.shape)

(10000, 12)
(10000,)

In [14]:
## Split data into train and test 
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [15]:
## Scale  these features 
scaler = StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [40]:
## Save the model 
with open('gender_encode.pkl','wb') as file:
    pickle.dump(label_encoder_gender,file)
with open('geo_encode.pkl','wb') as file:
    pickle.dump(onehot_encoder_geo,file)
with open('scaler_reg.pkl','wb') as file:
    pickle.dump(scaler,file)

## ANN Regression Problem Statement

In [17]:
import tensorflow as tf 
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense

In [25]:
## Build model 
model = Sequential([
    Dense(64,activation='relu',input_shape=(X_train.shape[1],)),
    Dense(32,activation='relu'),
    Dense(16,activation='relu'),
    Dense(8,activation='relu'),
    Dense(1) ## Output layer of regression 
])

## Compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense_23 (Dense)                     │ (None, 64)                  │             832 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_24 (Dense)                     │ (None, 32)                  │           2,080 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_25 (Dense)                     │ (None, 16)                  │             528 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_26 (Dense)                     │ (None, 8)                   │             136 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_27 (Dense)                     │ (None, 1)                   │               9 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 3,585 (14.00 KB)

 Trainable params: 3,585 (14.00 KB)

 Non-trainable params: 0 (0.00 B)

In [27]:
from tensorflow.keras.callbacks import EarlyStopping,TensorBoard 
import datetime 

# set up TensorBoard 
log_dir = 'regressionlogs/fit/' + datetime.datetime.now().strftime('%Y%m%d-%H%M%S')
tensorbaord_callback=TensorBoard(log_dir=log_dir,histogram_freq=1)

In [28]:
## Set up Early Stopping 
early_stopping_callback = EarlyStopping(monitor='val_loss',patience=10,restore_best_weights=True)

In [30]:
## Train the model 
history = model.fit(
    X_train,y_train,
    validation_data=(X_test,y_test),
    epochs=100,
    callbacks=[early_stopping_callback , tensorbaord_callback]
)

Epoch 1/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 7s 14ms/step - loss: 99654.7266 - mae: 99654.7266 - val_loss: 93891.5547 - val_mae: 93891.5547
Epoch 2/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 70673.8672 - mae: 70673.8672 - val_loss: 50935.6758 - val_mae: 50935.6758
Epoch 3/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 50250.4453 - mae: 50250.4453 - val_loss: 50357.5781 - val_mae: 50357.5781
Epoch 4/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49914.2305 - mae: 49914.2305 - val_loss: 50279.4102 - val_mae: 50279.4102
Epoch 5/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49801.9336 - mae: 49801.9336 - val_loss: 50257.2969 - val_mae: 50257.2969
Epoch 6/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 10ms/step - loss: 49728.4375 - mae: 49728.4375 - val_loss: 50246.9805 - val_mae: 50246.9805
Epoch 7/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49671.8789 - mae: 49671.8789 - val_loss: 50244.0469 - val_mae: 50244.0469
Epoch 8/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49628.6836 - mae: 49628.6836 - val_loss: 50254.6992 - val_mae: 50254.6992
Epoch 9/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49588.0352 - mae: 49588.0352 - val_loss: 50262.0352 - val_mae: 50262.0352
Epoch 10/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 9ms/step - loss: 49555.8008 - mae: 49555.8008 - val_loss: 50262.1641 - val_mae: 50262.1641
Epoch 11/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49526.2109 - mae: 49526.2109 - val_loss: 50262.5156 - val_mae: 50262.5156
Epoch 12/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 9ms/step - loss: 49500.1055 - mae: 49500.1055 - val_loss: 50268.0547 - val_mae: 50268.0547
Epoch 13/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - loss: 49479.2734 - mae: 49479.2734 - val_loss: 50276.0898 - val_mae: 50276.0898
Epoch 14/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 1382s 6s/step - loss: 49459.6992 - mae: 49459.6992 - val_loss: 50282.6797 - val_mae: 50282.6797
Epoch 15/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 3s 12ms/step - loss: 49438.6680 - mae: 49438.6680 - val_loss: 50288.3203 - val_mae: 50288.3203
Epoch 16/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 5s 13ms/step - loss: 49419.5508 - mae: 49419.5508 - val_loss: 50296.3945 - val_mae: 50296.3945
Epoch 17/100
250/250 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - loss: 49403.4414 - mae: 49403.4414 - val_loss: 50312.3125 - val_mae: 50312.3125

In [31]:
%load_ext tensorboard

In [37]:
%tensorboard --logdir regressionlogs/fit/20261001-162915

In [38]:
## Evaluate this model for our test data 

test_loss , test_mae = model.evaluate(X_test,y_test)
print(f'test mae : {test_mae}')

63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 8ms/step - loss: 50244.0469 - mae: 50244.0469
test mae : 50244.046875

In [39]:
model.save('regression_model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [44]:
X.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,0,0.0,0.0,1.0