In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt 
%matplotlib inline

In [3]:
df=pd.read_csv('social_medias.csv')

In [4]:
df.head()

,User_ID,User_Name,Platform,Date,State,Region,Followers,Views,Likes,Shares,Comments,Revenue_Source
0,USR00001,user_1,YouTube,2021-02-12,West Virginia,West,2768080,19372860,850362,38235,80095,Merchandise
1,USR00002,user_2,Snapchat,2020-07-05,South Carolina,South,362527,5875394,1325481,29621,79445,Affiliate
2,USR00003,user_3,Snapchat,2021-09-11,New York,East,2251888,9359073,3424727,116032,75694,Ads
3,USR00004,user_4,Instagram,2021-11-24,Colorado,North,3712496,8732120,1634073,127578,95973,Subscription
4,USR00005,user_5,Instagram,2020-12-01,Arkansas,Central,4000874,12114183,225983,75912,40832,Ads

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   User_ID         10000 non-null  object
 1   User_Name       10000 non-null  object
 2   Platform        10000 non-null  object
 3   Date            10000 non-null  object
 4   State           10000 non-null  object
 5   Region          10000 non-null  object
 6   Followers       10000 non-null  int64
 7   Views           10000 non-null  int64
 8   Likes           10000 non-null  int64
 9   Shares          10000 non-null  int64
 10  Comments        10000 non-null  int64
 11  Revenue_Source  10000 non-null  object
dtypes: int64(5), object(7)
memory usage: 937.6+ KB

In [7]:
df.shape

(10000, 12)

In [8]:
df.describe()

          Followers         Views         Likes         Shares      Comments
count  1.000000e+04  1.000000e+04  1.000000e+04   10000.000000  10000.000000
mean   2.489762e+06  1.000282e+07  2.485798e+06  250869.305400  49543.427800
std    1.452740e+06  5.786472e+06  1.446776e+06  144284.031913  28849.421008
min    6.450000e+02  1.039000e+03  3.750000e+02      22.000000      1.000000
25%    1.238559e+06  5.034581e+06  1.233954e+06  125936.000000  24725.750000
50%    2.475331e+06  1.002077e+07  2.460526e+06  251470.000000  49164.000000
75%    3.765367e+06  1.505416e+07  3.730236e+06  376672.250000  74258.000000
max    4.999457e+06  1.999992e+07  4.999896e+06  499948.000000  99987.000000

In [9]:
df.isnull().sum()

User_ID           0
User_Name         0
Platform          0
Date              0
State             0
Region            0
Followers         0
Views             0
Likes             0
Shares            0
Comments          0
Revenue_Source    0
dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
df.head()

,User_ID,User_Name,Platform,Date,State,Region,Followers,Views,Likes,Shares,Comments,Revenue_Source
0,USR00001,user_1,YouTube,2021-02-12,West Virginia,West,2768080,19372860,850362,38235,80095,Merchandise
1,USR00002,user_2,Snapchat,2020-07-05,South Carolina,South,362527,5875394,1325481,29621,79445,Affiliate
2,USR00003,user_3,Snapchat,2021-09-11,New York,East,2251888,9359073,3424727,116032,75694,Ads
3,USR00004,user_4,Instagram,2021-11-24,Colorado,North,3712496,8732120,1634073,127578,95973,Subscription
4,USR00005,user_5,Instagram,2020-12-01,Arkansas,Central,4000874,12114183,225983,75912,40832,Ads

In [15]:
df['Platform'].value_counts()

Platform
YouTube      2046
Instagram    2027
Twitter      2000
Facebook     1973
Snapchat     1954
Name: count, dtype: int64

In [11]:
x_train,x_test,y_train,y_test = train_test_split(df)

ValueError: not enough values to unpack (expected 4, got 2)