## Used Car Price Prediction 
 ### 1) Problem Statement 
 . This dataset comprises used cars sold on cardekho.com in india as well important features of these cars.
 
 . If user can predict the price of the care based on input features.
 
 . Prediction result can be used to give new seller the price sugestion based on market condition 


 ### 2) Data Collection . 
 . The Dataset is collected from scrapping from cardheko website 
 
 . The Data consist of 13 column and 15411 rows

In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import plotly.express as px
import warnings 
warnings.filterwarnings('ignore')
%matplotlib inline

In [2]:
df=pd.read_csv('cardekho_imputated.csv',index_col=[0])
df.head()

,car_name,brand,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Maruti Alto,Maruti,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Hyundai Grand,Hyundai,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,Hyundai i20,Hyundai,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Maruti Alto,Maruti,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ford Ecosport,Ford,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

## Data Cleaning 
1. Handling Missing Values
2. Handling Duplicates
3. Check Data type
4. Understand the dataset

In [3]:
## Check Numm Values
### Check Features with nan value 
df.isnull().sum()

car_name             0
brand                0
model                0
vehicle_age          0
km_driven            0
seller_type          0
fuel_type            0
transmission_type    0
mileage              0
engine               0
max_power            0
seats                0
selling_price        0
dtype: int64

In [4]:
df.dtypes

car_name              object
brand                 object
model                 object
vehicle_age            int64
km_driven              int64
seller_type           object
fuel_type             object
transmission_type     object
mileage              float64
engine                 int64
max_power            float64
seats                  int64
selling_price          int64
dtype: object

In [5]:
## Remove unnecessary columns 
df.drop('car_name',axis=1,inplace=True)
df.drop('brand',axis=1,inplace=True)

In [6]:
df.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats,selling_price
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5,120000
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5,550000
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5,215000
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5,226000
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5,570000

In [7]:
df['model'].unique()

array(['Alto', 'Grand', 'i20', 'Ecosport', 'Wagon R', 'i10', 'Venue',
       'Swift', 'Verna', 'Duster', 'Cooper', 'Ciaz', 'C-Class', 'Innova',
       'Baleno', 'Swift Dzire', 'Vento', 'Creta', 'City', 'Bolero',
       'Fortuner', 'KWID', 'Amaze', 'Santro', 'XUV500', 'KUV100', 'Ignis',
       'RediGO', 'Scorpio', 'Marazzo', 'Aspire', 'Figo', 'Vitara',
       'Tiago', 'Polo', 'Seltos', 'Celerio', 'GO', '5', 'CR-V',
       'Endeavour', 'KUV', 'Jazz', '3', 'A4', 'Tigor', 'Ertiga', 'Safari',
       'Thar', 'Hexa', 'Rover', 'Eeco', 'A6', 'E-Class', 'Q7', 'Z4', '6',
       'XF', 'X5', 'Hector', 'Civic', 'D-Max', 'Cayenne', 'X1', 'Rapid',
       'Freestyle', 'Superb', 'Nexon', 'XUV300', 'Dzire VXI', 'S90',
       'WR-V', 'XL6', 'Triber', 'ES', 'Wrangler', 'Camry', 'Elantra',
       'Yaris', 'GL-Class', '7', 'S-Presso', 'Dzire LXI', 'Aura', 'XC',
       'Ghibli', 'Continental', 'CR', 'Kicks', 'S-Class', 'Tucson',
       'Harrier', 'X3', 'Octavia', 'Compass', 'CLS', 'redi-GO', 'Glanza',
       'Macan', 'X4', 'Dzire ZXI', 'XC90', 'F-PACE', 'A8', 'MUX',
       'GTC4Lusso', 'GLS', 'X-Trail', 'XE', 'XC60', 'Panamera', 'Alturas',
       'Altroz', 'NX', 'Carnival', 'C', 'RX', 'Ghost', 'Quattroporte',
       'Gurkha'], dtype=object)

In [8]:
## Getting ALl Different Types Of Features 
num_features=[feature for feature in df.columns if df[feature].dtype != 'O']
print('Num of Numerical Features : ' , len(num_features))
cat_features=[feature for feature in df.columns if df[feature].dtype == 'O']
print('Num of Categorical Features : ', len(cat_features))
discrete_features=[feature for feature in num_features if len(df[feature].unique())<=25]
print('Num of Discrete Features : ' , len(discrete_features))
continuous_features=[feature for feature in num_features if feature not in discrete_features]
print('Num of Continuous Features : ' , len(continuous_features))

Num of Numerical Features :  7
Num of Categorical Features :  4
Num of Discrete Features :  2
Num of Continuous Features :  5

In [9]:
## Independent and dependent features

from sklearn.model_selection import train_test_split
x=df.drop(['selling_price'],axis=1)
y=df['selling_price']

In [10]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,Alto,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,Grand,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,i20,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,Alto,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,Ecosport,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

## Feature Encoding and Scaling 
#### One Hot Encoding for Columns which had lesser unique value and not ordinal 
One Hot Encoding is a process by which categorical variables are covered into a from that could be provided to ML algorithms to do a better job in prediction.

In [11]:
len(df['model'].unique())

120

In [12]:
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder()
x['model']=le.fit_transform(x['model'])

In [13]:
x.head()

,model,vehicle_age,km_driven,seller_type,fuel_type,transmission_type,mileage,engine,max_power,seats
0,7,9,120000,Individual,Petrol,Manual,19.70,796,46.30,5
1,54,5,20000,Individual,Petrol,Manual,18.90,1197,82.00,5
2,118,11,60000,Individual,Petrol,Manual,17.00,1197,80.00,5
3,7,9,37000,Individual,Petrol,Manual,20.92,998,67.10,5
4,38,6,30000,Dealer,Diesel,Manual,22.77,1498,98.59,5

In [14]:
len(df['transmission_type'].unique()),len(df['seller_type'].unique()),len(df['fuel_type'].unique())

(2, 3, 5)

In [15]:
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from sklearn.compose import ColumnTransformer

# numeric columns
nums_features = x.select_dtypes(exclude='object').columns

# categorical columns
onehot_columns = ['seller_type', 'fuel_type', 'transmission_type']

# transformers
numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

# column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('OneHotEncoder', oh_transformer, onehot_columns),
        ('StandardScaler', numeric_transformer, nums_features)
    ],
    remainder='passthrough'
)

In [16]:
x=preprocessor.fit_transform(x)

In [17]:
pd.DataFrame(x).head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,1.247335,-0.000276,-1.324259,-1.263352,-0.403022
1,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-0.225693,-0.343933,-0.690016,-0.192071,-0.554718,-0.432571,-0.403022
2,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.536377,1.647309,0.084924,-0.647583,-0.554718,-0.479113,-0.403022
3,1.0,0.0,0.0,0.0,0.0,1.0,1.0,-1.519714,0.983562,-0.360667,0.292211,-0.936610,-0.779312,-0.403022
4,0.0,0.0,1.0,0.0,0.0,0.0,1.0,-0.666211,-0.012060,-0.496281,0.735736,0.022918,-0.046502,-0.403022

In [18]:
# Separate Dataset into train and test 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=10)

## Model Traning And Model Selection

In [19]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.linear_model import LinearRegression,Ridge,Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error,r2_score

In [20]:
## Create a Function to Evaluate Model 
def evaluate_model(true,predicted):
    mae=mean_absolute_error(true,predicted)
    mse=mean_squared_error(true,predicted)
    rmse=np.sqrt(mean_squared_error(true,predicted))
    r2_square=r2_score(true,predicted(true,predicted))
    
    return mae,rmse,r2_square

In [21]:
def evaluate_model(true, predicted):
    mae = mean_absolute_error(true, predicted)
    rmse = np.sqrt(mean_squared_error(true, predicted))
    r2_square = r2_score(true, predicted)   # FIXED

    return mae, rmse, r2_square

In [22]:
## Beginning Model Training 
models = {
    'Linear Regression': LinearRegression(),
    'Lasso': Lasso(),
    'Ridge': Ridge(),
    'K-Neighbors Regressor': KNeighborsRegressor(),
    'Decision Tree': DecisionTreeRegressor(),
    'Random Forest Regressor': RandomForestRegressor(),
}

for i in range(len(models)):
    model = list(models.values())[i]     # FIXED
    name = list(models.keys())[i]

    # Train model
    model.fit(x_train, y_train)

    # Make Predictions 
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    # Evaluate Train and Test Dataset 
    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print("\n================== {} ==================\n".format(name))

    print("Model Performance For Training Set")
    print("- RMSE : {:.4f}".format(model_train_rmse))
    print("- MAE  : {:.4f}".format(model_train_mae))
    print("- R2   : {:.4f}".format(model_train_r2))

    print("\nModel Performance For Test Set")
    print("- RMSE : {:.4f}".format(model_test_rmse))
    print("- MAE  : {:.4f}".format(model_test_mae))
    print("- R2   : {:.4f}".format(model_test_r2))

    print("=" * 40)
    print('\n')

================== Linear Regression ==================

Model Performance For Training Set
- RMSE : 479969.7756
- MAE  : 259213.6221
- R2   : 0.6714

Model Performance For Test Set
- RMSE : 705736.8923
- MAE  : 272529.8041
- R2   : 0.5450
========================================

================== Lasso ==================

Model Performance For Training Set
- RMSE : 479969.7804
- MAE  : 259211.7833
- R2   : 0.6714

Model Performance For Test Set
- RMSE : 705736.5145
- MAE  : 272528.6365
- R2   : 0.5450
========================================

================== Ridge ==================

Model Performance For Training Set
- RMSE : 479970.4545
- MAE  : 259181.2139
- R2   : 0.6714

Model Performance For Test Set
- RMSE : 705754.4142
- MAE  : 272511.7411
- R2   : 0.5449
========================================

================== K-Neighbors Regressor ==================

Model Performance For Training Set
- RMSE : 237731.1084
- MAE  : 89245.5637
- R2   : 0.9194

Model Performance For Test Set
- RMSE : 554358.8629
- MAE  : 117546.7428
- R2   : 0.7192
========================================

================== Decision Tree ==================

Model Performance For Training Set
- RMSE : 19459.6521
- MAE  : 4706.3102
- R2   : 0.9995

Model Performance For Test Set
- RMSE : 520222.2775
- MAE  : 131565.9183
- R2   : 0.7528
========================================

================== Random Forest Regressor ==================

Model Performance For Training Set
- RMSE : 91921.1385
- MAE  : 38500.7580
- R2   : 0.9879

Model Performance For Test Set
- RMSE : 481962.3220
- MAE  : 106574.0353
- R2   : 0.7878
========================================

In [23]:
# Initaialize few parameter for hyperparameter  tuning 
knn_params={'n_neighbors':[2,3,10,20,40,50]}
rf_params={'max_depth':[5,8,15,None,10],
           'max_features':[5,7,'auto',8],
           'min_samples_split':[2,8,15,20],
           'n_estimators':[100,200,500,1000]}

In [24]:
## Model List for Hypermarameter Tuning 
randomcv_models=[('KNN',KNeighborsRegressor(),knn_params),
                 ('RF'  ,RandomForestRegressor(),rf_params)
                ]

In [28]:
# Hyperparameter Tuning 
from sklearn.model_selection import RandomizedSearchCV

model_param={}
for name,model,params in randomcv_models:
    random=RandomizedSearchCV(
        estimator=model,
        param_distributions=params,
        n_iter=100,
        cv=3,
        verbose=2,
        n_jobs=1
    )
    random.fit(x_train,y_train)
    model_param[name]=random.best_params_

for model_name in model_param:
    print(f'---------------------Best Params For     {model_name}-----------------')
    print(model_param[model_name])

Fitting 3 folds for each of 6 candidates, totalling 18 fits
[CV] END ......................................n_neighbors=2; total time=   0.2s
[CV] END ......................................n_neighbors=2; total time=   0.2s
[CV] END ......................................n_neighbors=2; total time=   0.2s
[CV] END ......................................n_neighbors=3; total time=   0.3s
[CV] END ......................................n_neighbors=3; total time=   0.3s
[CV] END ......................................n_neighbors=3; total time=   0.5s
[CV] END .....................................n_neighbors=10; total time=   0.5s
[CV] END .....................................n_neighbors=10; total time=   0.4s
[CV] END .....................................n_neighbors=10; total time=   0.5s
[CV] END .....................................n_neighbors=20; total time=   0.7s
[CV] END .....................................n_neighbors=20; total time=   0.7s
[CV] END .....................................n_neighbors=20; total time=   0.7s
[CV] END .....................................n_neighbors=40; total time=   1.0s
[CV] END .....................................n_neighbors=40; total time=   0.9s
[CV] END .....................................n_neighbors=40; total time=   1.0s
[CV] END .....................................n_neighbors=50; total time=   1.1s
[CV] END .....................................n_neighbors=50; total time=   1.0s
[CV] END .....................................n_neighbors=50; total time=   1.0s
Fitting 3 folds for each of 100 candidates, totalling 300 fits
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=200; total time=   6.5s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=200; total time=   6.8s
[CV] END max_depth=15, max_features=7, min_samples_split=15, n_estimators=200; total time=   6.9s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=500; total time=  13.4s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=500; total time=  14.2s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=500; total time=  13.0s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=100; total time=   2.6s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=100; total time=   2.7s
[CV] END max_depth=None, max_features=5, min_samples_split=20, n_estimators=100; total time=   2.5s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=100; total time=   1.5s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=100; total time=   1.7s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=100; total time=   1.9s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=  13.4s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=  12.8s
[CV] END max_depth=8, max_features=8, min_samples_split=20, n_estimators=500; total time=  13.3s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=100; total time=   4.4s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=100; total time=   4.5s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=100; total time=   4.4s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=100; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=1000; total time=  33.4s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=1000; total time=  31.6s
[CV] END max_depth=None, max_features=7, min_samples_split=20, n_estimators=1000; total time=  34.4s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=1000; total time=  17.2s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=1000; total time=  16.7s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=1000; total time=  16.5s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=200; total time=   7.2s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=200; total time=   7.1s
[CV] END max_depth=None, max_features=8, min_samples_split=20, n_estimators=200; total time=   7.2s
[CV] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=200; total time=   5.0s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=200; total time=   5.0s
[CV] END max_depth=15, max_features=5, min_samples_split=20, n_estimators=200; total time=   4.9s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=1000; total time=  29.5s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=1000; total time=  29.5s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=1000; total time=  27.1s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=500; total time=  10.0s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=500; total time=  10.2s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=500; total time=  10.4s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=  21.6s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=  21.0s
[CV] END max_depth=None, max_features=5, min_samples_split=2, n_estimators=500; total time=  22.8s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=100; total time=   1.1s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=100; total time=   1.1s
[CV] END max_depth=5, max_features=5, min_samples_split=15, n_estimators=100; total time=   1.1s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   5.1s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   5.1s
[CV] END max_depth=10, max_features=7, min_samples_split=15, n_estimators=200; total time=   5.2s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=15, max_features=auto, min_samples_split=20, n_estimators=1000; total time=   0.0s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=1000; total time=  59.8s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=1000; total time=  46.6s
[CV] END max_depth=None, max_features=8, min_samples_split=2, n_estimators=1000; total time=  57.6s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=   9.9s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=  10.6s
[CV] END max_depth=None, max_features=7, min_samples_split=2, n_estimators=200; total time=  11.3s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=500; total time=   6.9s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=500; total time=   8.3s
[CV] END max_depth=5, max_features=7, min_samples_split=15, n_estimators=500; total time=   8.2s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=200; total time=   8.4s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=200; total time=   8.1s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=200; total time=   8.5s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=500; total time=   0.0s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=200; total time=   5.0s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=200; total time=   4.3s
[CV] END max_depth=10, max_features=5, min_samples_split=15, n_estimators=200; total time=   4.0s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=200; total time=   5.3s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=200; total time=   6.0s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=200; total time=   5.6s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=  11.1s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=  13.7s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=500; total time=  11.4s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   1.3s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   1.1s
[CV] END max_depth=5, max_features=7, min_samples_split=2, n_estimators=100; total time=   1.4s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=2, n_estimators=500; total time=   0.0s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=500; total time=  12.2s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=500; total time=  12.1s
[CV] END max_depth=8, max_features=7, min_samples_split=2, n_estimators=500; total time=  11.6s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=500; total time=  13.0s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=500; total time=  12.4s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=500; total time=  12.8s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=None, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=100; total time=   3.2s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=100; total time=   3.5s
[CV] END max_depth=15, max_features=5, min_samples_split=2, n_estimators=100; total time=   3.7s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=1000; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=2, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100; total time=   2.1s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100; total time=   2.4s
[CV] END max_depth=10, max_features=5, min_samples_split=8, n_estimators=100; total time=   2.3s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=100; total time=   2.3s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=100; total time=   2.3s
[CV] END max_depth=8, max_features=8, min_samples_split=15, n_estimators=100; total time=   2.3s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=1000; total time=  17.8s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=1000; total time=  19.9s
[CV] END max_depth=5, max_features=8, min_samples_split=20, n_estimators=1000; total time=  18.4s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=200; total time=   7.5s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=200; total time=   7.5s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=200; total time=   7.5s
[CV] END max_depth=10, max_features=5, min_samples_split=2, n_estimators=200; total time=   5.0s
[CV] END max_depth=10, max_features=5, min_samples_split=2, n_estimators=200; total time=   5.0s
[CV] END max_depth=10, max_features=5, min_samples_split=2, n_estimators=200; total time=   5.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=15, n_estimators=500; total time=   0.0s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=1000; total time=  20.0s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=1000; total time=  19.9s
[CV] END max_depth=5, max_features=8, min_samples_split=2, n_estimators=1000; total time=  19.9s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=  25.0s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=  25.5s
[CV] END max_depth=15, max_features=5, min_samples_split=15, n_estimators=1000; total time=  24.8s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=1000; total time=  23.8s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=1000; total time=  12.1s
[CV] END max_depth=8, max_features=7, min_samples_split=20, n_estimators=1000; total time=  19.7s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=auto, min_samples_split=8, n_estimators=200; total time=   0.0s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   2.5s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   2.6s
[CV] END max_depth=10, max_features=7, min_samples_split=8, n_estimators=100; total time=   2.6s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=1000; total time=  41.2s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=1000; total time=  41.6s
[CV] END max_depth=None, max_features=8, min_samples_split=8, n_estimators=1000; total time=  43.8s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=500; total time=  24.2s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=500; total time=  24.6s
[CV] END max_depth=15, max_features=8, min_samples_split=2, n_estimators=500; total time=  25.1s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=10, max_features=auto, min_samples_split=20, n_estimators=100; total time=   0.0s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=1000; total time=  40.1s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=1000; total time=  39.9s
[CV] END max_depth=None, max_features=7, min_samples_split=8, n_estimators=1000; total time=  40.5s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=1000; total time=  32.1s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=1000; total time=  31.6s
[CV] END max_depth=15, max_features=7, min_samples_split=20, n_estimators=1000; total time=  31.7s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=100; total time=   1.4s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=100; total time=   1.2s
[CV] END max_depth=5, max_features=5, min_samples_split=8, n_estimators=100; total time=   1.2s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=1000; total time=  45.3s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=1000; total time=  44.1s
[CV] END max_depth=15, max_features=7, min_samples_split=2, n_estimators=1000; total time=  44.2s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=500; total time=  11.8s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=500; total time=  11.3s
[CV] END max_depth=8, max_features=7, min_samples_split=15, n_estimators=500; total time=  11.8s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=8, max_features=auto, min_samples_split=15, n_estimators=200; total time=   0.0s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=500; total time=   6.6s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=500; total time=   6.5s
[CV] END max_depth=5, max_features=5, min_samples_split=20, n_estimators=500; total time=   6.0s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=1000; total time=  36.1s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=1000; total time=  35.8s
[CV] END max_depth=15, max_features=8, min_samples_split=15, n_estimators=1000; total time=  38.8s

In [31]:
## Retraining the models with best parameter
models={
    'Random Forest Regressor':RandomForestRegressor(n_estimators=500,min_samples_split=2,max_features=8,max_depth=None,n_jobs=1),
    # max_depth=15, max_features=7, min_samples_split=15, n_estimators=200
    'K-Neigbors Regressor':KNeighborsRegressor(n_neighbors=3,n_jobs=1)
}
for i in range(len(models)):
    model = list(models.values())[i]     # FIXED
    name = list(models.keys())[i]

    # Train model
    model.fit(x_train, y_train)

    # Make Predictions 
    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    # Evaluate Train and Test Dataset 
    model_train_mae, model_train_rmse, model_train_r2 = evaluate_model(y_train, y_train_pred)
    model_test_mae, model_test_rmse, model_test_r2 = evaluate_model(y_test, y_test_pred)

    print("\n================== {} ==================\n".format(name))

    print("Model Performance For Training Set")
    print("- RMSE : {:.4f}".format(model_train_rmse))
    print("- MAE  : {:.4f}".format(model_train_mae))
    print("- R2   : {:.4f}".format(model_train_r2))

    print("\nModel Performance For Test Set")
    print("- RMSE : {:.4f}".format(model_test_rmse))
    print("- MAE  : {:.4f}".format(model_test_mae))
    print("- R2   : {:.4f}".format(model_test_r2))

    print("=" * 40)

================== Random Forest Regressor ==================

Model Performance For Training Set
- RMSE : 94167.3784
- MAE  : 37990.6611
- R2   : 0.9873

Model Performance For Test Set
- RMSE : 487546.0977
- MAE  : 105235.4515
- R2   : 0.7828
========================================

================== K-Neigbors Regressor ==================

Model Performance For Training Set
- RMSE : 222360.7254
- MAE  : 77348.0778
- R2   : 0.9295

Model Performance For Test Set
- RMSE : 541315.4113
- MAE  : 117342.5037
- R2   : 0.7323
========================================

In [ ]:
import p