### Steps 
- Preprocessing and Cleaning
- Train test split
- BOW,TF-IDF,WOrd2vec
- Train ML Algorithms

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('amazon_product_reviews.csv',encoding='latin')

In [3]:
df.head()

,Review ID,text,Body,sentiment,Product id
0,1,Just OK but won't repurchase,I prefer candles to fragrance my home but want...,3,B09VTNCFKL
1,2,Good scent,Love this reed diffuser! This is a good altern...,5,B09VTNCFKL
2,3,"Overpowering, do not buy if you have pets!!","Update: the seller kindly refunded me, and tha...",1,B09VTNCFKL
3,4,Surprisingly lovely and fragrant,I bought based only on reviews - wanted someth...,5,B0CC3SZ5F4
4,5,Doesn't like heat,I'll start by saying the product is great. Sme...,5,B09VTNCFKL

In [4]:
x=df['Body']
y=df['sentiment']

In [5]:
d={
    'review':x,
    'rating':y
}
data=pd.DataFrame(d)

In [6]:
data.head()

                                              review  rating
0  I prefer candles to fragrance my home but want...       3
1  Love this reed diffuser! This is a good altern...       5
2  Update: the seller kindly refunded me, and tha...       1
3  I bought based only on reviews - wanted someth...       5
4  I'll start by saying the product is great. Sme...       5

In [7]:
data.shape

(1960, 2)

In [8]:
## Missing values 
data.isnull().sum()

review    0
rating    0
dtype: int64

In [9]:
data['rating'].unique()

array([3, 5, 1, 4, 2], dtype=int64)

In [10]:
a,b,c,d,e=data['rating'].value_counts()

In [19]:
p=[a,b,c,d,e]
q=[i for i in range(1,6)]
import matplotlib.pyplot as plt 
import seaborn as sns

In [27]:
sns.pairplot(data,height=5,markers='o',hue=['r','b',')

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()