In [1]:
## First you have to install the pandas library 
## you run the inside jupyter notebook : !pip install pandas 
## Command prompt : pip innstall pandas 

# then import the pandas library in the 
import pandas as pd

In [2]:
## Load the data set in the csv format 
## make sure your file must be csv format 
data=pd.read_csv('aids.csv')

In [3]:
data.head()

,Country,Year,Data.AIDS-Related Deaths.AIDS Orphans,Data.AIDS-Related Deaths.Adults,Data.AIDS-Related Deaths.All Ages,Data.AIDS-Related Deaths.Children,Data.AIDS-Related Deaths.Female Adults,Data.AIDS-Related Deaths.Male Adults,Data.HIV Prevalence.Adults,Data.HIV Prevalence.Young Men,...,Data.New HIV Infections.Female Adults,Data.New HIV Infections.Children,Data.New HIV Infections.All Ages,Data.New HIV Infections.Adults,Data.New HIV Infections.Incidence Rate Among Adults,Data.People Living with HIV.Total,Data.People Living with HIV.Male Adults,Data.People Living with HIV.Female Adults,Data.People Living with HIV.Children,Data.People Living with HIV.Adults
0,Afghanistan,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,100,100,500
1,Algeria,1990,200,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,200,100,500
2,Angola,1990,1300,500,1000,500,200,200,0.2,0.1,...,1700,1000,3400,2800,0.47,12000,4600,6100,1100,11000
3,Argentina,1990,500,200,500,100,100,200,0.1,0.1,...,1200,200,4500,4400,0.19,13000,9100,3700,200,13000
4,Armenia,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,100,100,100,100,100

In [4]:
data.head(2)

,Country,Year,Data.AIDS-Related Deaths.AIDS Orphans,Data.AIDS-Related Deaths.Adults,Data.AIDS-Related Deaths.All Ages,Data.AIDS-Related Deaths.Children,Data.AIDS-Related Deaths.Female Adults,Data.AIDS-Related Deaths.Male Adults,Data.HIV Prevalence.Adults,Data.HIV Prevalence.Young Men,...,Data.New HIV Infections.Female Adults,Data.New HIV Infections.Children,Data.New HIV Infections.All Ages,Data.New HIV Infections.Adults,Data.New HIV Infections.Incidence Rate Among Adults,Data.People Living with HIV.Total,Data.People Living with HIV.Male Adults,Data.People Living with HIV.Female Adults,Data.People Living with HIV.Children,Data.People Living with HIV.Adults
0,Afghanistan,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,100,100,500
1,Algeria,1990,200,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,200,100,500

In [5]:
df1=data.tail()

In [6]:
type(data)

pandas.core.frame.DataFrame

In [7]:
df1.to_csv('test.csv')

In [8]:
ls

 Volume in drive C is Local Disk
 Volume Serial Number is 845B-B5FF

 Directory of C:\Users\Madhav Yadav\OneDrive\Desktop\desktop1\Datascience_bootcamp\pandas

15-02-2026  09:30    <DIR>          .
19-02-2026  10:54    <DIR>          ..
15-02-2026  08:32    <DIR>          .ipynb_checkpoints
15-02-2026  07:28           457,895 aids.csv
15-02-2026  08:39            16,356 call_center.xlsx
15-02-2026  08:44            21,240 hist.xlsx
15-02-2026  09:30            89,518 Pandas_day_1.ipynb
15-02-2026  08:28               678 result.csv
15-02-2026  08:29               678 result2.csv
15-02-2026  08:33               131 result3.csv
19-02-2026  11:01             1,444 test.csv
               8 File(s)        587,940 bytes
               3 Dir(s)  38,154,575,872 bytes free

In [9]:
t= pd.read_csv('test.csv',header=None,names=['a','b','c','d','e','f','g','h'],skiprows=[0,3])

In [10]:
t

,,,,,,,,,,,,,,,,a,b,c,d,e,f,g,h
2754,Venezuela (Bolivarian Republic of),2020,39000,3900,4200,500,2500,1400,0.5,0.1,0.2,1800,1000,1000,500,2200,1900,0.09,100000,60000,40000,3300,99000
2755,Viet Nam,2020,83000,3700,3800,100,1000,2900,0.3,0.1,0.1,5300,3900,2000,500,6100,5900,0.08,250000,160000,80000,4300,240000
2757,Zambia,2020,700000,19000,24000,5300,10000,8700,11.1,2.3,6.0,58000,21000,39000,8300,69000,61000,6.07,1500000,520000,850000,82000,1400000
2758,Zimbabwe,2020,540000,19000,22000,3500,9500,9300,11.9,2.9,5.2,19000,7300,13000,5100,25000,20000,2.44,1300000,470000,720000,79000,1200000

In [12]:
# d=pd.read_csv('test.csv'na_values=1)

In [14]:
d=pd.read_excel('hist.xlsx')

In [15]:
d.describe()

       Unnamed: 0                        Unnamed: 1  Unnamed: 2  Unnamed: 3
count          84                                85     84.0000     84.0000
unique         84                                85     80.0000     83.0000
top          Year  Annual Returns on Investments in      0.0038      0.0466
freq            1                                 1      5.0000      2.0000

In [20]:
d.head()

  Unnamed: 0                        Unnamed: 1 Unnamed: 2 Unnamed: 3
0        NaN                               NaN        NaN        NaN
1        NaN                               NaN        NaN        NaN
2        NaN                               NaN        NaN        NaN
3        NaN                               NaN        NaN        NaN
4        NaN  Annual Returns on Investments in        NaN        NaN

In [17]:
d.to_csv('result2.csv',index=False,header=False,sep="#",)

In [21]:
d.to_csv('result3.csv',index=False,header=True,columns=['Unnamed: 0','Unnamed: 1','Unnamed: 2','Unnamed: 3'])

In [23]:
type(d['Unnamed: 1'])

pandas.core.series.Series

In [26]:
d[['Unnamed: 0','Unnamed: 1']].dtypes

Unnamed: 0    object
Unnamed: 1    object
dtype: object

In [27]:
import pandas as pd

In [28]:
aids=pd.read_csv('aids.csv')

In [29]:
aids.head()

,Country,Year,Data.AIDS-Related Deaths.AIDS Orphans,Data.AIDS-Related Deaths.Adults,Data.AIDS-Related Deaths.All Ages,Data.AIDS-Related Deaths.Children,Data.AIDS-Related Deaths.Female Adults,Data.AIDS-Related Deaths.Male Adults,Data.HIV Prevalence.Adults,Data.HIV Prevalence.Young Men,...,Data.New HIV Infections.Female Adults,Data.New HIV Infections.Children,Data.New HIV Infections.All Ages,Data.New HIV Infections.Adults,Data.New HIV Infections.Incidence Rate Among Adults,Data.People Living with HIV.Total,Data.People Living with HIV.Male Adults,Data.People Living with HIV.Female Adults,Data.People Living with HIV.Children,Data.People Living with HIV.Adults
0,Afghanistan,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,100,100,500
1,Algeria,1990,200,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,200,100,500
2,Angola,1990,1300,500,1000,500,200,200,0.2,0.1,...,1700,1000,3400,2800,0.47,12000,4600,6100,1100,11000
3,Argentina,1990,500,200,500,100,100,200,0.1,0.1,...,1200,200,4500,4400,0.19,13000,9100,3700,200,13000
4,Armenia,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,100,100,100,100,100

In [30]:
# We have to able to save the thiese file for the different file extenxion 
aids.to_html('aids.html')

In [31]:
## Read the html file 
read_html= pd.read_html('aids.html')

In [39]:
from_file = pd.read_csv('aids.csv')

In [40]:
from_file.to_pickle('my_pickle')

In [41]:
pwd()

'C:\\Users\\Madhav Yadav\\OneDrive\\Desktop\\desktop1\\Datascience_bootcamp\\pandas'

In [42]:
from_file

,Country,Year,Data.AIDS-Related Deaths.AIDS Orphans,Data.AIDS-Related Deaths.Adults,Data.AIDS-Related Deaths.All Ages,Data.AIDS-Related Deaths.Children,Data.AIDS-Related Deaths.Female Adults,Data.AIDS-Related Deaths.Male Adults,Data.HIV Prevalence.Adults,Data.HIV Prevalence.Young Men,...,Data.New HIV Infections.Female Adults,Data.New HIV Infections.Children,Data.New HIV Infections.All Ages,Data.New HIV Infections.Adults,Data.New HIV Infections.Incidence Rate Among Adults,Data.People Living with HIV.Total,Data.People Living with HIV.Male Adults,Data.People Living with HIV.Female Adults,Data.People Living with HIV.Children,Data.People Living with HIV.Adults
0,Afghanistan,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,100,100,500
1,Algeria,1990,200,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,200,100,500
2,Angola,1990,1300,500,1000,500,200,200,0.2,0.1,...,1700,1000,3400,2800,0.47,12000,4600,6100,1100,11000
3,Argentina,1990,500,200,500,100,100,200,0.1,0.1,...,1200,200,4500,4400,0.19,13000,9100,3700,200,13000
4,Armenia,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,100,100,100,100,100
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2754,Venezuela (Bolivarian Republic of),2020,39000,3900,4200,500,2500,1400,0.5,0.1,...,1000,500,2200,1900,0.09,100000,60000,40000,3300,99000
2755,Viet Nam,2020,83000,3700,3800,100,1000,2900,0.3,0.1,...,2000,500,6100,5900,0.08,250000,160000,80000,4300,240000
2756,Yemen,2020,5500,500,500,100,100,200,0.1,0.1,...,500,100,1100,1000,0.05,11000,6300,3700,1000,10000
2757,Zambia,2020,700000,19000,24000,5300,10000,8700,11.1,2.3,...,39000,8300,69000,61000,6.07,1500000,520000,850000,82000,1400000
2758,Zimbabwe,2020,540000,19000,22000,3500,9500,9300,11.9,2.9,...,13000,5100,25000,20000,2.44,1300000,470000,720000,79000,1200000

In [53]:
df1 = pd.DataFrame([[1, 2], [3, 4]], columns=["A", "B"])
df2 = pd.DataFrame([[5, 6], [7, 8]], columns=["C", "D"])

In [54]:
store = pd.HDFStore("store.h5", "w")

ImportError: Missing optional dependency 'pytables'.  Use pip or conda to install pytables.

In [48]:
!pip install pytable

Collecting pytable
  Downloading pytable-0.8.23a.zip (264 kB)
  Downloading pytable-0.8.22a.zip (264 kB)
  Downloading pytable-0.8.21a.tar.gz (200 kB)

The conflict is caused by:
    pytable 0.8.23a0 depends on basicproperty>=0.6.9a
    pytable 0.8.22a0 depends on basicproperty>=0.6.9a
    pytable 0.8.21a0 depends on basicproperty>=0.6.9a

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: Cannot install pytable==0.8.21a0, pytable==0.8.22a0 and pytable==0.8.23a0 because these package versions have conflicting dependencies.
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
WARNING: You are using pip version 21.2.3; however, version 26.0.1 is available.
You should consider upgrading via the 'C:\Users\Madhav Yadav\OneDrive\Desktop\desktop1\Datascience_bootcamp\nlp\nlpvenv\Scripts\python.exe -m pip install --upgrade pip' command.

In [49]:
!pip install --upgrade pip

Requirement already satisfied: pip in c:\users\madhav yadav\onedrive\desktop\desktop1\datascience_bootcamp\nlp\nlpvenv\lib\site-packages (21.2.3)
Collecting pip
  Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 21.2.3
    Uninstalling pip-21.2.3:
      Successfully uninstalled pip-21.2.3

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\Madhav Yadav\\AppData\\Local\\Temp\\pip-uninstall-3up1_0r_\\pip.exe'
Check the permissions.

In [50]:
pwd()

'C:\\Users\\Madhav Yadav\\OneDrive\\Desktop\\desktop1\\Datascience_bootcamp\\pandas'