In [4]:
## First you have to install the pandas library 
## you run the inside jupyter notebook : !pip install pandas 
## Command prompt : pip innstall pandas 

# then import the pandas library in the 
import pandas as pd

In [10]:
## Load the data set in the csv format 
## make sure your file must be csv format 
data=pd.read_csv('aids.csv')

In [11]:
data.head()

,Country,Year,Data.AIDS-Related Deaths.AIDS Orphans,Data.AIDS-Related Deaths.Adults,Data.AIDS-Related Deaths.All Ages,Data.AIDS-Related Deaths.Children,Data.AIDS-Related Deaths.Female Adults,Data.AIDS-Related Deaths.Male Adults,Data.HIV Prevalence.Adults,Data.HIV Prevalence.Young Men,...,Data.New HIV Infections.Female Adults,Data.New HIV Infections.Children,Data.New HIV Infections.All Ages,Data.New HIV Infections.Adults,Data.New HIV Infections.Incidence Rate Among Adults,Data.People Living with HIV.Total,Data.People Living with HIV.Male Adults,Data.People Living with HIV.Female Adults,Data.People Living with HIV.Children,Data.People Living with HIV.Adults
0,Afghanistan,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,100,100,500
1,Algeria,1990,200,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,200,100,500
2,Angola,1990,1300,500,1000,500,200,200,0.2,0.1,...,1700,1000,3400,2800,0.47,12000,4600,6100,1100,11000
3,Argentina,1990,500,200,500,100,100,200,0.1,0.1,...,1200,200,4500,4400,0.19,13000,9100,3700,200,13000
4,Armenia,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,100,100,100,100,100

In [12]:
data.head(2)

,Country,Year,Data.AIDS-Related Deaths.AIDS Orphans,Data.AIDS-Related Deaths.Adults,Data.AIDS-Related Deaths.All Ages,Data.AIDS-Related Deaths.Children,Data.AIDS-Related Deaths.Female Adults,Data.AIDS-Related Deaths.Male Adults,Data.HIV Prevalence.Adults,Data.HIV Prevalence.Young Men,...,Data.New HIV Infections.Female Adults,Data.New HIV Infections.Children,Data.New HIV Infections.All Ages,Data.New HIV Infections.Adults,Data.New HIV Infections.Incidence Rate Among Adults,Data.People Living with HIV.Total,Data.People Living with HIV.Male Adults,Data.People Living with HIV.Female Adults,Data.People Living with HIV.Children,Data.People Living with HIV.Adults
0,Afghanistan,1990,100,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,100,100,500
1,Algeria,1990,200,100,100,100,100,100,0.1,0.1,...,100,100,100,100,0.01,500,500,200,100,500

In [16]:
df1=data.tail()

In [15]:
type(data)

pandas.core.frame.DataFrame

In [17]:
df1.to_csv('test.csv')

In [18]:
ls

 Volume in drive C is Local Disk
 Volume Serial Number is 845B-B5FF

 Directory of C:\Users\Madhav Yadav\OneDrive\Desktop\desktop1\Datascience_bootcamp\pandas

15-02-2026  07:41    <DIR>          .
15-02-2026  07:20    <DIR>          ..
15-02-2026  07:20    <DIR>          .ipynb_checkpoints
15-02-2026  07:28           457,895 aids.csv
15-02-2026  07:40            20,058 Pandas_day_1.ipynb
15-02-2026  07:41             1,444 test.csv
               3 File(s)        479,397 bytes
               3 Dir(s)  41,016,020,992 bytes free

In [32]:
t= pd.read_csv('test.csv',header=None,names=['a','b','c','d','e','f','g','h'],skiprows=[0,3])

In [33]:
t

,,,,,,,,,,,,,,,,a,b,c,d,e,f,g,h
2754,Venezuela (Bolivarian Republic of),2020,39000,3900,4200,500,2500,1400,0.5,0.1,0.2,1800,1000,1000,500,2200,1900,0.09,100000,60000,40000,3300,99000
2755,Viet Nam,2020,83000,3700,3800,100,1000,2900,0.3,0.1,0.1,5300,3900,2000,500,6100,5900,0.08,250000,160000,80000,4300,240000
2757,Zambia,2020,700000,19000,24000,5300,10000,8700,11.1,2.3,6.0,58000,21000,39000,8300,69000,61000,6.07,1500000,520000,850000,82000,1400000
2758,Zimbabwe,2020,540000,19000,22000,3500,9500,9300,11.9,2.9,5.2,19000,7300,13000,5100,25000,20000,2.44,1300000,470000,720000,79000,1200000

In [34]:
d=pd.read_csv('test.csv'na_values=1)

In [36]:
d

,Unnamed: 0,Country,Year,Data.AIDS-Related Deaths.AIDS Orphans,Data.AIDS-Related Deaths.Adults,Data.AIDS-Related Deaths.All Ages,Data.AIDS-Related Deaths.Children,Data.AIDS-Related Deaths.Female Adults,Data.AIDS-Related Deaths.Male Adults,Data.HIV Prevalence.Adults,...,Data.New HIV Infections.Female Adults,Data.New HIV Infections.Children,Data.New HIV Infections.All Ages,Data.New HIV Infections.Adults,Data.New HIV Infections.Incidence Rate Among Adults,Data.People Living with HIV.Total,Data.People Living with HIV.Male Adults,Data.People Living with HIV.Female Adults,Data.People Living with HIV.Children,Data.People Living with HIV.Adults
0,2754,Venezuela (Bolivarian Republic of),2020,39000,3900,4200,500,2500,1400,0.5,...,1000,500,2200,1900,0.09,100000,60000,40000,3300,99000
1,2755,Viet Nam,2020,83000,3700,3800,100,1000,2900,0.3,...,2000,500,6100,5900,0.08,250000,160000,80000,4300,240000
2,2756,Yemen,2020,5500,500,500,100,100,200,0.1,...,500,100,1100,1000,0.05,11000,6300,3700,1000,10000
3,2757,Zambia,2020,700000,19000,24000,5300,10000,8700,11.1,...,39000,8300,69000,61000,6.07,1500000,520000,850000,82000,1400000
4,2758,Zimbabwe,2020,540000,19000,22000,3500,9500,9300,11.9,...,13000,5100,25000,20000,2.44,1300000,470000,720000,79000,1200000

In [38]:
d.describe()

,Unnamed: 0,Year,Data.AIDS-Related Deaths.AIDS Orphans,Data.AIDS-Related Deaths.Adults,Data.AIDS-Related Deaths.All Ages,Data.AIDS-Related Deaths.Children,Data.AIDS-Related Deaths.Female Adults,Data.AIDS-Related Deaths.Male Adults,Data.HIV Prevalence.Adults,Data.HIV Prevalence.Young Men,...,Data.New HIV Infections.Female Adults,Data.New HIV Infections.Children,Data.New HIV Infections.All Ages,Data.New HIV Infections.Adults,Data.New HIV Infections.Incidence Rate Among Adults,Data.People Living with HIV.Total,Data.People Living with HIV.Male Adults,Data.People Living with HIV.Female Adults,Data.People Living with HIV.Children,Data.People Living with HIV.Adults
count,5.000000,5.0,5.000000,5.00000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000e+00,5.000000,5.000000,5.000000,5.000000e+00
mean,2756.000000,2020.0,273500.000000,9220.00000,10900.000000,1900.000000,4620.000000,4500.000000,4.780000,1.100000,...,11100.000000,2900.000000,20680.000000,17960.000000,1.746000,6.322000e+05,243260.000000,338740.000000,33920.000000,5.898000e+05
std,1.581139,0.0,322501.550384,9029.23031,11161.093136,2374.868417,4764.136858,4223.150483,6.142638,1.385641,...,16425.589792,3652.396474,28683.392407,25236.937215,2.625496,7.096191e+05,236992.907067,410849.653766,42551.580464,6.573015e+05
min,2754.000000,2020.0,5500.000000,500.00000,500.000000,100.000000,100.000000,200.000000,0.100000,0.100000,...,500.000000,100.000000,1100.000000,1000.000000,0.050000,1.100000e+04,6300.000000,3700.000000,1000.000000,1.000000e+04
25%,2755.000000,2020.0,39000.000000,3700.00000,3800.000000,100.000000,1000.000000,1400.000000,0.300000,0.100000,...,1000.000000,500.000000,2200.000000,1900.000000,0.080000,1.000000e+05,60000.000000,40000.000000,3300.000000,9.900000e+04
50%,2756.000000,2020.0,83000.000000,3900.00000,4200.000000,500.000000,2500.000000,2900.000000,0.500000,0.100000,...,2000.000000,500.000000,6100.000000,5900.000000,0.090000,2.500000e+05,160000.000000,80000.000000,4300.000000,2.400000e+05
75%,2757.000000,2020.0,540000.000000,19000.00000,22000.000000,3500.000000,9500.000000,8700.000000,11.100000,2.300000,...,13000.000000,5100.000000,25000.000000,20000.000000,2.440000,1.300000e+06,470000.000000,720000.000000,79000.000000,1.200000e+06
max,2758.000000,2020.0,700000.000000,19000.00000,24000.000000,5300.000000,10000.000000,9300.000000,11.900000,2.900000,...,39000.000000,8300.000000,69000.000000,61000.000000,6.070000,1.500000e+06,520000.000000,850000.000000,82000.000000,1.400000e+06

In [40]:
d.dtypes

Unnamed: 0                                               int64
Country                                                 object
Year                                                     int64
Data.AIDS-Related Deaths.AIDS Orphans                    int64
Data.AIDS-Related Deaths.Adults                          int64
Data.AIDS-Related Deaths.All Ages                        int64
Data.AIDS-Related Deaths.Children                        int64
Data.AIDS-Related Deaths.Female Adults                   int64
Data.AIDS-Related Deaths.Male Adults                     int64
Data.HIV Prevalence.Adults                             float64
Data.HIV Prevalence.Young Men                          float64
Data.HIV Prevalence.Young Women                        float64
Data.New HIV Infections.Young Adults                     int64
Data.New HIV Infections.Male Adults                      int64
Data.New HIV Infections.Female Adults                    int64
Data.New HIV Infections.Children                         int64
Data.New HIV Infections.All Ages                         int64
Data.New HIV Infections.Adults                           int64
Data.New HIV Infections.Incidence Rate Among Adults    float64
Data.People Living with HIV.Total                        int64
Data.People Living with HIV.Male Adults                  int64
Data.People Living with HIV.Female Adults                int64
Data.People Living with HIV.Children                     int64
Data.People Living with HIV.Adults                       int64
dtype: object

In [45]:
d.to_csv('result2.csv',index=False,header=False,sep="#",)

In [53]:
d.to_csv('result3.csv',index=False,header=True,columns=['Data.AIDS-Related Deaths.AIDS Orphans',
                                                         'Data.AIDS-Related Deaths.Children'])

In [58]:
type(d['Data.AIDS-Related Deaths.Children'])

pandas.core.series.Series

In [59]:
type(d[['Data.AIDS-Related Deaths.Children']])

pandas.core.frame.DataFrame

In [60]:
d[['Data.AIDS-Related Deaths.Children','Data.AIDS-Related Deaths.AIDS Orphans']]

   Data.AIDS-Related Deaths.Children  Data.AIDS-Related Deaths.AIDS Orphans
0                                500                                  39000
1                                100                                  83000
2                                100                                   5500
3                               5300                                 700000
4                               3500                                 540000

In [69]:
d5=pd.read_excel('hist.xlsx')

HTTPError: HTTP Error 403: Forbidden

Collecting lxml
  Using cached lxml-6.0.2-cp310-cp310-win_amd64.whl.metadata (3.7 kB)
Using cached lxml-6.0.2-cp310-cp310-win_amd64.whl (4.0 MB)
Installing collected packages: lxml
Successfully installed lxml-6.0.2